version: '2.1'


orbs:
  install-orb: bozhos/install-orb@2.2.1


jobs:
  deploy:
    executor: install-orb/default
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "add ingress rule to aws sg"
          environment:
            PARAM_APP_DIRECTORY: "deployapp"
          command: | 
                    pwd
                    ls -la
                    PUBLIC_IP=$(curl ipinfo.io/ip)
                    ~/bin/aws ec2 authorize-security-group-ingress --region $AWS_DEFAULT_REGION --group-id $SG_ID --protocol tcp --port 22 --cidr $PUBLIC_IP/32
                    sleep 5
                    ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS  "sudo systemctl stop test-app.service"
                    cat $PARAM_APP_DIRECTORY_$CIRCLE_SHA1.zip | ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "cat > $PARAM_APP_DIRECTORY_$CIRCLE_SHA1.zip"
                    ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "sudo unzip -o $PARAM_APP_DIRECTORY_$CIRCLE_SHA1.zip -d /opt/"
                    ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS  "sudo systemctl start test-app.service"


workflows:
  test-my-orb:
    jobs:
      - install-orb/install
      - deploy:
          context: 
            - aws-context
          requires:
            - install-orb/install
