version: '2.1'


orbs:
  install-orb: bozhos/install-orb@3.3.0

jobs:
  install:
    executor: install-orb/default
    steps:
      - checkout
      - install-orb/install:
          dotnet_version: "3.1"
          app_directory: "deployapp"
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: install-orb/default
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - attach_workspace:
          at: .
      - install-orb/deploy:
          app_directory: "deployapp"
      - run:
          name: "scp and unzip app"
          command: |
                    pwd
                    ls -la
                    ssh -o StrictHostKeyChecking=no ubuntu@"$EC2_PUBLIC_DNS"  "sudo systemctl stop test-app.service"
                    echo "stopped test-app service"
                    cat deployapp_$CIRCLE_SHA1.zip | ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_DNS "cat > deployapp_$CIRCLE_SHA1.zip"
                    echo "copied zip to ec2"
                    ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_DNS "sudo unzip -o deployapp_$CIRCLE_SHA1.zip -d /opt/" 
                    echo "unzipped zip at /opt"
                    ssh -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_DNS  "sudo systemctl start test-app.service"
                    echo "started test-app service"
                    PUBLIC_IP=$(curl ipinfo.io/ip)
                    sudo ~/bin/aws ec2 revoke-security-group-ingress --region $AWS_DEFAULT_REGION --group-id $SG_ID --protocol tcp --port 22 --cidr $PUBLIC_IP/24
                    echo "removed ingress rule"
         
workflows:
  test-my-orb:
    jobs:
      - install
      - deploy:
          context: 
            - aws-context
          requires:
            - install
