version: '2.1'
orbs:
  install-orb: bozhos/install-orb@2.2.1

jobs:
  deploy:
    executor: install-orb/default
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "add ingress rule to aws sg"
          command: | 
                    pwd
                    ls -la

workflows:
  test-my-orb:
    jobs:
      - install-orb/install:
          dotnet_version: "3.1"
          app_directory: "deploynewapp"
      - deploy:
          requires:
            - install-orb/install
