version: '2.1'
orbs:
  install-orb: bozhos/install-orb@2.1.0
workflows:
  test-my-orb:
    jobs:
      - install-orb/install:
          dotnet_version: "3.1"
          app_directory: "deploynewapp"
    